version: "3.9"

services:
  db:
    image: exemple
    environment:
      POSTGRES_USER: exemple
      POSTGRES_PASSWORD: exemple
      POSTGRES_DB: exemple
    ports:
      - "exemple:exemple"
    volumes:
      - exemple

  api:
    build: .
    command: >
      sh -c "
        sleep 5 &&
        go run ./cmd/seed/main.go &&
        go run ./cmd/api
        "
    env_file:
      - .env
    ports:
      - "exemple:exemple"
    depends_on:
      - db
    

volumes:
  pgdata: